### PR TITLE
Add support for Ruby 2.7.0

### PR DESCRIPTION
**Pull request by raxod502**
Same as https://github.com/ruby-syntax-tree/syntax_tree-rbs/pull/34 which is the same as https://github.com/ruby-syntax-tree/syntax_tree/pull/148. I'm really having the time of my life fixing CI this month.

### CODE REVIEW

**Comment by raxod502** [comment]
Hmm, looks like CI is failing due to an error that was introduced with the haml 6.0 breaking changes merged in https://github.com/ruby-syntax-tree/syntax_tree-haml/pull/31. Same error [here](https://github.com/ruby-syntax-tree/syntax_tree-haml/actions/runs/3101850527/jobs/5023602339).

**Comment by raxod502** [comment]
Asked a question upstream at https://github.com/haml/haml/issues/1085.

**Comment by raxod502** [comment]
If we can always assume that the parser will be available in haml 6.x, then my latest commit should get things passing again. It bumps the Gemfile to require haml 6.x and then simplifies the code/tests to remove that check.

**Comment by kddnewton** [comment]
Ahh I'd like to support Haml 5 still. Can you check if the method is defined with `respond_to?` and if it's not then assume it's available?

**Comment by kddnewton** [comment]
Also feel free to convert this to a regular PR not a draft, this is good. Also thank you for fixing the CI on all this stuff.

**Comment by raxod502** [comment]
Thanks to upstream change in haml 6.0.1 per https://github.com/haml/haml/issues/1085, we should be able to continue using the existing API, so reverted my last commit.

**Comment by raxod502** [comment]
Unit tests are now passing locally for me.

**Comment by raxod502** [comment]
I think you might need to publish a new release for this as well, 1.3.3 is on main but not on rubygems.

**Pull request merged**
